### ISSUE TITLE
Process about rel path

### ISSUE THREAD

**Issue by leejunho-com** [week-end-manufacture/incoming#20]
<img width="832" alt="image" src="https://github.com/week-end-manufacture/incoming/assets/91662691/03964446-23ea-4ca9-b820-90a854354ff1">

⬆️ Condition
```bash
$ incoming -i "vidoe.mkv" -o "video.mp4"
# or 
$ incoming -i "vidoe.mkv" -o "../output"
```
Possible? or just abs path?

**Comment by JoHyukJun** [comment]
Pull and test it
