### ISSUE TITLE
Goal of archive files (post_processing)

### ISSUE THREAD

**Issue by leejunho-com** [week-end-manufacture/incoming#23]
## example
<img width="848" alt="Screenshot 2024-05-25 at 14 34 59" src="https://github.com/week-end-manufacture/incoming/assets/91662691/6297baea-ca77-4eac-a603-69b89d8391f4">

1. Copy not include image file in archive
2. Extract archive file and remove when process is done.
3. Locate "src archive file name + _ext" in same relpath.

**Comment by JoHyukJun** [comment]
post + pre processor updated.
