### ISSUE TITLE
exif, gps 데이터 삭제됨

### ISSUE THREAD

**Issue by leejunho-com** [week-end-manufacture/incoming#25]
https://github.com/week-end-manufacture/incoming/blob/0f571f368e29ba4c4e4036eb6ccb4c23c7c7ac17/ic_image.py#L25-L47

- 35, 38라인 

1. preset.json에서 두 값 모두 false
2. 그럼에도 이미지처리된 사진 메타데이터는 모두 삭제
3. 색공간도 srgb로 강제적으로 변경됨

**Comment by JoHyukJun** [comment]
test done. get from org.
